"""CLI entrypoint for local AlphaGenome serving."""

from __future__ import annotations

import argparse
import logging
import sys
import time

import torch

from alphagenome_pytorch import AlphaGenome
from alphagenome_pytorch.variant_scoring.inference import VariantScoringModel

from .adapter import LocalDnaModelAdapter
from .grpc_service import serve_grpc
from .rest_service import serve_rest

LOGGER = logging.getLogger(__name__)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog='alphagenome-local-serve',
        description='Serve AlphaGenome predictions/scoring locally over gRPC and optional REST.',
    )
    parser.add_argument('--weights', required=True, help='Path to AlphaGenome PyTorch weights file.')
    parser.add_argument('--fasta', required=True, help='Path to reference FASTA file.')
    parser.add_argument('--gtf', default=None, help='Optional GTF/Parquet annotations path.')
    parser.add_argument('--polya', default=None, help='Optional polyA annotations path.')
    parser.add_argument(
        '--track-metadata',
        default=None,
        help='Optional parquet metadata file generated by extract_track_metadata.py.',
    )
    parser.add_argument('--device', default='cpu', help='Torch device (e.g., cpu, cuda:0).')
    parser.add_argument('--host', default='127.0.0.1', help='Bind host for serving endpoints.')

    parser.add_argument('--grpc-port', type=int, default=50051, help='gRPC server port.')
    parser.add_argument('--disable-grpc', action='store_true', help='Disable gRPC server.')

    parser.add_argument(
        '--rest-port',
        type=int,
        default=None,
        help='REST server port (disabled when not provided).',
    )
    parser.add_argument(
        '--log-level',
        default='INFO',
        choices=['DEBUG', 'INFO', 'WARNING', 'ERROR'],
        help='Logging level.',
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format='%(asctime)s %(levelname)s %(name)s - %(message)s',
    )

    model = AlphaGenome(num_organisms=2)
    state_dict = torch.load(args.weights, map_location=args.device, weights_only=True)
    model.load_state_dict(state_dict, strict=False)
    model.to(args.device)
    model.eval()

    scoring_model = VariantScoringModel(
        model=model,
        fasta_path=args.fasta,
        gtf_path=args.gtf,
        polya_path=args.polya,
        device=args.device,
    )
    if args.track_metadata:
        scoring_model.load_all_metadata(args.track_metadata)

    adapter = LocalDnaModelAdapter(scoring_model)

    grpc_server = None
    if not args.disable_grpc:
        grpc_server = serve_grpc(adapter, host=args.host, port=args.grpc_port, wait=False)
        LOGGER.info('gRPC ready at %s:%d', args.host, args.grpc_port)

    rest_server = None
    if args.rest_port is not None:
        rest_server = serve_rest(adapter, host=args.host, port=args.rest_port, wait=False)
        LOGGER.info('REST ready at http://%s:%d', args.host, args.rest_port)

    if grpc_server is None and rest_server is None:
        parser.error('At least one transport must be enabled (gRPC or REST).')

    try:
        while True:
            time.sleep(1.0)
    except KeyboardInterrupt:
        LOGGER.info('Shutting down local serving...')
        if grpc_server is not None:
            grpc_server.stop(grace=3.0)
        if rest_server is not None:
            rest_server.shutdown()
            rest_server.server_close()
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv[1:]))

